<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv=Content-Type content="text/html; charset=windows-1252">
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 12">
<link rel=File-List href="calltracking_files/filelist.xml">
<style>
			table.grid{}
			td.header { background-color:#2182bf;font-family:Arial;font-weight:bold;color:#f1f5f8;font-size:12px;padding:5px;} 
			td.content { padding:2px;height:24px;font-family:Arial;font-weight:normal;color:#456376;font-size:12px;background-color:#f9fbfd;}
			td.toprank { padding:2px;height:24px;font-family:Arial;font-weight:normal;color:#456376;font-size:12px;background-color:#FFFF00;}
			td.first {border-left:1px solid #dddddd;border-top:1px solid #dddddd;border-bottom:0px solid #dddddd;}
			td.middle {border-left:1px solid #dddddd;border-bottom:0px solid #dddddd;border-top:1px solid #dddddd;}
			td.lasted {border-left:1px solid #dddddd; border-bottom:0px solid #dddddd; border-right:1px solid #dddddd; border-top:1px solid #dddddd;}
			td.agent{font-family:Arial;font-weight:normal;font-size:12px;padding-top:5px;padding-bottom:5px;border-left:0px solid #dddddd; 
					border-bottom:0px solid #dddddd; border-right:0px solid #dddddd; border-top:0px solid #dddddd;
					background-color:#fcfeff;padding-left:2px;color:#06456d;font-weight:bold;}
			h1.agent{font-style:inherit; font-family:Trebuchet MS;color:blue;}
			
			td.total{
						padding:2px;font-family:Arial;font-weight:normal;font-size:12px;padding-top:5px;padding-bottom:5px;border-left:0px solid #dddddd; 
					border-bottom:1px solid #dddddd; border-top:1px solid #dddddd;  
					border-right:1px solid #dddddd; border-top:1px solid #dddddd;
					background-color:#2182bf;padding-left:2px;color:#f1f5f8;font-weight:bold;}
			span.top{color:#306407;font-family:Trebuchet MS;font-size:16px;line-height:18px;}
			span.middle{color:#306407;font-family:Trebuchet MS;font-size:14px;line-height:18px;}
			span.bottom{color:#306407;font-family:Trebuchet MS;font-size:12px;line-height:18px;}
			td.subtotal{ font-family:Arial;font-weight:bold;color:#3c8a08;height:30px;background-color:#FFFCCC;}
			td.tanggal{ font-weight:bold;color:#FF4321;height:22px;background-color:#FFFFFF;height:30px;}
			h3{color:#306407;font-family:Trebuchet MS;font-size:14px;}
			h4{color:#FF4321;font-family:Trebuchet MS;font-size:14px;}
			span.warning-text{font-family:Arial;font-size:12px;color:red;}
		</style>	
</head>

<body>
<!--[if !excel]>&nbsp;&nbsp;<![endif]-->
<!--The following information was generated by Microsoft Office Excel's Publish
as Web Page wizard.-->
<!--If the same item is republished from Excel, all information between the DIV
tags will be replaced.-->
<!----------------------------->
<!--START OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD -->
<!----------------------------->

<div id="Book1_24732" align=center x:publishsource="Excel">

<table class="grid" cellpadding="0" cellspacing="0" width="90%">

 <tr>
  <td align="center" rowspan=3 class="header first">Campaign</td>
  <td align="center" colspan=4 class="header middle">Record Data</td>
  <td align="center" rowspan=3 class="header middle">Call Attempt</td>
  <td align="center" rowspan=3 class="header middle">AVG Call / Record</td>
  <td align="center" colspan=5 class="header middle">Connect</td>
  <td align="center" rowspan=3 class="header middle">Connected Rate %</td>
  <td align="center" colspan=7 class="header middle">Contact</td>
  <td align="center" rowspan=3 class="header middle">Contact Rate %</td>
  <td align="center" colspan=2 class="header middle">Follow Up</td>
  <td align="center" colspan=11 class="header middle">Interest</td>
  <td align="center" rowspan=3 class="header middle">Response Rate %</td>
  <td align="center" rowspan=3 class="header middle">Conversion Rate %</td>
  <td align="center"colspan=5 class="header middle">Not Qualifield</td>
  <td align="center" rowspan=3 class="header middle">SALES</td>
  <td align="center" rowspan=3 class="header middle">TARP</td>
  <td align="center" rowspan=3 class="header middle">TARGET</td>
  <td align="center" rowspan=3 class="header middle">ACTUAL TARGET</td>
  <td align="center" rowspan=3 class="header lasted">VARIANCE TARGET</td>
 </tr>
 <tr>
  <td rowspan=2 class="header middle" align="center">New</td>
  <td rowspan=2 class="header middle" align="center">ReAssigned</td>
  <td rowspan=2 class="header middle" align="center">UnAssigned</td>
  <td rowspan=2 class="header middle" align="center">Utilized</td>
  <td rowspan=2 class="header middle" align="center">Yes</td>
  <td colspan=4 class="header middle" align="center">Not Connect</td>
  <td rowspan=2 class="header middle" align="center">Yes</td>
  <td colspan=6 class="header middle" align="center">Not Contact</td>
  <td rowspan=2 class="header middle" align="center">301</td>
  <td rowspan=2 class="header middle" align="center">302</td>
  <td colspan=3 class="header middle" align="center">Yes</td>
  <td colspan=8 class="header middle" align="center">Not Interest</td>
  <td rowspan=2 class="header middle" align="center">501</td>
  <td rowspan=2 class="header middle" align="center">502</td>
  <td rowspan=2 class="header middle" align="center">503</td>
  <td rowspan=2 class="header middle" align="center">504</td>
  <td rowspan=2 class="header middle" align="center">505</td>
 </tr>
 <tr>
  <td class="header middle" align="center">101</td>
  <td class="header middle" align="center">102</td>
  <td class="header middle" align="center">103</td>
  <td class="header middle" align="center">104</td>
  <td class="header middle" align="center">201</td>
  <td class="header middle" align="center">202</td>
  <td class="header middle" align="center">203</td>
  <td class="header middle" align="center">204</td>
  <td class="header middle" align="center">205</td>
  <td class="header middle" align="center">206</td>
  <td class="header middle" align="center">901</td>
  <td class="header middle" align="center">902</td>
  <td class="header middle" align="center">903</td>
  <td class="header middle" align="center">401</td>
  <td class="header middle" align="center">402</td>
  <td class="header middle" align="center">403</td>
  <td class="header middle" align="center">404</td>
  <td class="header middle" align="center">405</td>
  <td class="header middle" align="center">406</td>
  <td class="header middle" align="center">407</td>
  <td class="header middle" align="center">408</td>
 </tr>

 <tr height=0 style='display:none'>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
 </tr>
 
 <tbody>
// <?php 
// $no = 1;
// $total_calls = 0;
// $total_connected = 0;
// $total_abandone = 0;
// $total_talk =0;
// foreach( $param['AgentId'] as $num => $AgentId ) :
	// $Agents				= $Users[$AgentId];
	// $color 				= ($no%2!=0?'#FFFEEE':'#FFFFFF');
	// $percent_connected 	= ($view[$AgentId]['tots']?(round($view[$AgentId]['tot_connected']/$view[$AgentId]['tots'],2)*100) : 0);
	// $percent_abandone 	= ($view[$AgentId]['tots']?(round($view[$AgentId]['tot_abandone']/$view[$AgentId]['tots'],2)*100) : 0);
	// $talktime_agent 	= _getDuration(($view[$AgentId]['tot_talk']?$view[$AgentId]['tot_talk']:0)); 						
	// $avg_talk_time		= _getDuration(($view[$AgentId]['tots']?($view[$AgentId]['tot_talk']/$view[$AgentId]['tot_connected']):0));
	
// ?>
<!--<tr>
	<td class="content-first">&nbsp;<#?php __($no);?></td>
	<td class="content-middle left">&nbsp;okokok<#?php __($Agents['name']);?></td>
	<td class="content-middle right">&nbsp;<#?php __(($view[$AgentId]['tots']?$view[$AgentId]['tots']:0));?></td>
	<td class="content-middle right">&nbsp;dsdsds<#?php __(($view[$AgentId]['tot_abandone']?$view[$AgentId]['tot_abandone']:0));?></td>
	<td class="content-middle right">&nbsp;<#?php __(($view[$AgentId]['tot_connected']?$view[$AgentId]['tot_connected']:0));?></td>
	<td class="content-middle right">&nbsp;<#?php __(($view[$AgentId]['tot_abandone']?$view[$AgentId]['tot_abandone']:0));?></td>
	<td class="content-middle right">&nbsp;<#?php __(($view[$AgentId]['tot_abandone']?$view[$AgentId]['tot_abandone']:0));?></td>
	<td class="content-middle right">&nbsp;<#?php __(($view[$AgentId]['tot_abandone']?$view[$AgentId]['tot_abandone']:0));?></td>
	<td class="content-middle right">&nbsp;<#?php __(($view[$AgentId]['tot_abandone']?$view[$AgentId]['tot_abandone']:0));?></td>
	<td class="content-middle right">&nbsp;<#?php __(($view[$AgentId]['tot_abandone']?$view[$AgentId]['tot_abandone']:0));?></td>
	<td class="content-middle right">&nbsp;<#?php __(($view[$AgentId]['tot_abandone']?$view[$AgentId]['tot_abandone']:0));?></td>
	<td class="content-middle right">&nbsp;<#?php __(($view[$AgentId]['tot_abandone']?$view[$AgentId]['tot_abandone']:0));?></td>
	<td class="content-middle right">&nbsp;<#?php __(($view[$AgentId]['tot_abandone']?$view[$AgentId]['tot_abandone']:0));?></td>
	<td class="content-middle right">&nbsp;<#?php __(($view[$AgentId]['tot_abandone']?$view[$AgentId]['tot_abandone']:0));?></td>
	<td class="content-middle right">&nbsp;<#?php __(($view[$AgentId]['tot_abandone']?$view[$AgentId]['tot_abandone']:0));?></td>
	<td class="content-middle right">&nbsp;<#?php __(($view[$AgentId]['tot_abandone']?$view[$AgentId]['tot_abandone']:0));?></td>
	<td class="content-middle right">&nbsp;<#?php __(($view[$AgentId]['tot_abandone']?$view[$AgentId]['tot_abandone']:0));?></td>
	<td class="content-middle right">&nbsp;<#?php __(($view[$AgentId]['tot_abandone']?$view[$AgentId]['tot_abandone']:0));?></td>
	<td class="content-middle right">&nbsp;<#?php __(($view[$AgentId]['tot_abandone']?$view[$AgentId]['tot_abandone']:0));?></td>
	<td class="content-middle right">&nbsp;<#?php __(($view[$AgentId]['tot_abandone']?$view[$AgentId]['tot_abandone']:0));?></td>
	<td class="content-middle right">&nbsp;<#?php __(($view[$AgentId]['tot_abandone']?$view[$AgentId]['tot_abandone']:0));?></td>
	<td class="content-middle right">&nbsp;<#?php __(($view[$AgentId]['tot_abandone']?$view[$AgentId]['tot_abandone']:0));?></td>
	<td class="content-middle right">&nbsp;<#?php __(($view[$AgentId]['tot_abandone']?$view[$AgentId]['tot_abandone']:0));?></td>
	<td class="content-middle right">&nbsp;<#?php __(($view[$AgentId]['tot_abandone']?$view[$AgentId]['tot_abandone']:0));?></td>
	<td class="content-middle right">&nbsp;<#?php __(($view[$AgentId]['tot_abandone']?$view[$AgentId]['tot_abandone']:0));?></td>
	<td class="content-middle right">&nbsp;<#?php __($percent_connected);?></td>
	<td class="content-middle right">&nbsp;<#?php __($percent_abandone);?></td>
	<td class="content-middle right">&nbsp;<#?php __($talktime_agent);?></td>
	<td class="content-lasted right">&nbsp;<#?php __($avg_talk_time);?></td>
</tr>-->
<tr onselect>
<td class="content-first">&nbsp;0</td>
<td class="content-middle right">&nbsp;0</td>
<td class="content-middle right">&nbsp;0</td>
<td class="content-lasted right">&nbsp;0</td>
<td class="content-lasted right">&nbsp;0</td>
<td class="content-lasted right">&nbsp;0</td>
<td class="content-lasted right">&nbsp;0</td>
<td class="content-lasted right">&nbsp;0</td>
<td class="content-lasted right">&nbsp;0</td>
<td class="content-lasted right">&nbsp;0</td>
<td class="content-lasted right">&nbsp;0</td>
<td class="content-lasted right">&nbsp;0</td>
<td class="content-lasted right">&nbsp;0</td>
<td class="content-lasted right">&nbsp;0</td>
<td class="content-lasted right">&nbsp;0</td>
<td class="content-lasted right">&nbsp;0</td>
<td class="content-lasted right">&nbsp;0</td>
<td class="content-lasted right">&nbsp;0</td>
<td class="content-lasted right">&nbsp;0</td>
<td class="content-lasted right">&nbsp;0</td>
<td class="content-lasted right">&nbsp;0</td>
<td class="content-lasted right">&nbsp;0</td>
<td class="content-lasted right">&nbsp;0</td>
<td class="content-lasted right">&nbsp;0</td>
<td class="content-lasted right">&nbsp;0</td>
<td class="content-lasted right">&nbsp;0</td>
<td class="content-lasted right">&nbsp;0</td>
<td class="content-lasted right">&nbsp;0</td>
<td class="content-lasted right">&nbsp;0</td>
<td class="content-lasted right">&nbsp;0</td>
<td class="content-lasted right">&nbsp;0</td>
<td class="content-lasted right">&nbsp;0</td>
<td class="content-lasted right">&nbsp;0</td>
<td class="content-lasted right">&nbsp;0</td>
<td class="content-lasted right">&nbsp;0</td>
<td class="content-lasted right">&nbsp;0</td>
<td class="content-lasted right">&nbsp;0</td>
<td class="content-lasted right">&nbsp;0</td>
<td class="content-lasted right">&nbsp;0</td>
<td class="content-lasted right">&nbsp;0</td>
<td class="content-lasted right">&nbsp;0</td>
<td class="content-lasted right">&nbsp;0</td>
<td class="content-lasted right">&nbsp;0</td>
<td class="content-lasted right">&nbsp;0</td>
<td class="content-lasted right">&nbsp;0</td>
<td class="content-lasted right">&nbsp;0</td>

<?php 

$total_calls 	 += $view[$AgentId]['tots'];
$total_connected += $view[$AgentId]['tot_connected'];
$total_abandone  += $view[$AgentId]['tot_abandone'];
$total_talk 	 += $view[$AgentId]['tot_talk'];
$no++; 
// endforeach;

print_r($_REQUEST);
$tots_percent_connected = ($total_calls?(round($total_connected/$total_calls,2)*100) : 0);
$tots_percent_abandone 	= ($total_calls?(round($total_abandone/$total_calls,2)*100) : 0);
$tots_talktime_agent 	= _getDuration(($total_talk?$total_talk:0)); 						
$tots_avg_talk_time		= _getDuration(($total_talk?$total_talk/$total_connected:0));

?>
<tr height='22' bgcolor='#eaf6fa'>
	<td class="content-first">&nbsp;<b>Total</b></td>
	<td class="content-middle right">&nbsp;<b><?php __($total_calls);?></b></td>
	<td class="content-middle right">&nbsp;<b><?php __($total_connected);?></b></td>
	<td class="content-middle right">&nbsp;<b><?php __($total_abandone);?></b></td>
	<td class="content-middle right">&nbsp;<b><?php __($tots_percent_connected);?></b></td>
	<td class="content-middle right">&nbsp;<b><?php __($tots_percent_abandone);?></b></td>
	<td class="content-middle right">&nbsp;<b><?php __($tots_talktime_agent );?></b></td>
	<td class="content-middle right">&nbsp;<b><?php __($total_calls);?></b></td>
	<td class="content-middle right">&nbsp;<b><?php __($total_calls);?></b></td>
	<td class="content-middle right">&nbsp;<b><?php __($total_calls);?></b></td>
	<td class="content-middle right">&nbsp;<b><?php __($total_calls);?></b></td>
	<td class="content-middle right">&nbsp;<b><?php __($total_calls);?></b></td>
	<td class="content-middle right">&nbsp;<b><?php __($total_calls);?></b></td>
	<td class="content-middle right">&nbsp;<b><?php __($total_calls);?></b></td>
	<td class="content-middle right">&nbsp;<b><?php __($total_calls);?></b></td>
	<td class="content-middle right">&nbsp;<b><?php __($total_calls);?></b></td>
	<td class="content-middle right">&nbsp;<b><?php __($total_calls);?></b></td>
	<td class="content-middle right">&nbsp;<b><?php __($total_calls);?></b></td>
	<td class="content-middle right">&nbsp;<b><?php __($total_calls);?></b></td>
	<td class="content-middle right">&nbsp;<b><?php __($total_calls);?></b></td>
	<td class="content-middle right">&nbsp;<b><?php __($total_calls);?></b></td>
	<td class="content-middle right">&nbsp;<b><?php __($total_calls);?></b></td>
	<td class="content-middle right">&nbsp;<b><?php __($total_calls);?></b></td>
	<td class="content-middle right">&nbsp;<b><?php __($total_calls);?></b></td>
	<td class="content-middle right">&nbsp;<b><?php __($total_calls);?></b></td>
	<td class="content-middle right">&nbsp;<b><?php __($total_calls);?></b></td>
	<td class="content-middle right">&nbsp;<b><?php __($total_calls);?></b></td>
	<td class="content-middle right">&nbsp;<b><?php __($total_calls);?></b></td>
	<td class="content-middle right">&nbsp;<b><?php __($total_calls);?></b></td>
	<td class="content-middle right">&nbsp;<b><?php __($total_calls);?></b></td>
	<td class="content-middle right">&nbsp;<b><?php __($total_calls);?></b></td>
	<td class="content-middle right">&nbsp;<b><?php __($total_calls);?></b></td>
	<td class="content-middle right">&nbsp;<b><?php __($total_calls);?></b></td>
	<td class="content-middle right">&nbsp;<b><?php __($total_calls);?></b></td>
	<td class="content-middle right">&nbsp;<b><?php __($total_calls);?></b></td>
	<td class="content-middle right">&nbsp;<b><?php __($total_calls);?></b></td>
	<td class="content-middle right">&nbsp;<b><?php __($total_calls);?></b></td>
	<td class="content-middle right">&nbsp;<b><?php __($total_calls);?></b></td>
	<td class="content-middle right">&nbsp;<b><?php __($total_calls);?></b></td>
	<td class="content-middle right">&nbsp;<b><?php __($total_calls);?></b></td>
	<td class="content-middle right">&nbsp;<b><?php __($total_calls);?></b></td>
	<td class="content-middle right">&nbsp;<b><?php __($total_calls);?></b></td>
	<td class="content-middle right">&nbsp;<b><?php __($total_calls);?></b></td>
	<td class="content-middle right">&nbsp;<b><?php __($total_calls);?></b></td>
	<td class="content-middle right">&nbsp;<b><?php __($total_calls);?></b></td>
	<td class="content-middle right">&nbsp;<b><?php __($total_calls);?></b></td>
	<td class="content-lasted right">&nbsp;<b><?php __($tots_avg_talk_time);?></b></td>
</tr>

</tbody>
</table>
</table>

</div>


<!----------------------------->
<!--END OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD-->
<!----------------------------->
</body>

</html>
