<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<title> Detail Sales Report </title>
<meta http-equiv=Content-Type content="text/html; charset=windows-1252">
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 12">
<link rel=File-List href="calltracking_files/filelist.xml">
<style>
			table.grid{}
			td.header { background-color:#2182bf;font-family:Arial;font-weight:bold;color:#f1f5f8;font-size:12px;padding:5px;} 
			td.content { padding:2px;height:24px;font-family:Arial;font-weight:normal;color:#456376;font-size:12px;background-color:#f9fbfd;}
			td.toprank { padding:2px;height:24px;font-family:Arial;font-weight:normal;color:#456376;font-size:12px;background-color:#FFFF00;}
			td.first {border-left:1px solid #dddddd;border-top:1px solid #dddddd;border-bottom:0px solid #dddddd;}
			td.middle {border-left:1px solid #dddddd;border-bottom:0px solid #dddddd;border-top:1px solid #dddddd;}
			td.lasted {border-left:1px solid #dddddd; border-bottom:0px solid #dddddd; border-right:1px solid #dddddd; border-top:1px solid #dddddd;}
			td.agent{font-family:Arial;font-weight:normal;font-size:12px;padding-top:5px;padding-bottom:5px;border-left:0px solid #dddddd; 
					border-bottom:0px solid #dddddd; border-right:0px solid #dddddd; border-top:0px solid #dddddd;
					background-color:#fcfeff;padding-left:2px;color:#06456d;font-weight:bold;}
			h1.agent{font-style:inherit; font-family:Trebuchet MS;color:blue;}
			.banner {
				font-family:Arial;font-weight:normal;color:#006600;font-size:15px;
			}
			.judul {
				font-family:Arial;font-weight:normal;color:#006600;font-size:15px;
			}
			hr {
			display: block;
			margin-top: 0.5em;
			margin-bottom: 0.5em;
			margin-left: auto;
			margin-right: auto;
			border-style: inset;
			border-widht: 1px;
			border-color: $f1f5f8;
			}			
		</style>	
</head>

<!-- <html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv=Content-Type content="text/html; charset=windows-1252">
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 12">
<link rel=File-List href="REPORT%20DETAIL%20SALES%20RESULT_files/filelist.xml">
<style id="REPORT DETAIL SALES RESULT_23545_Styles"></style>
</head> -->

<body>
<!--[if !excel]>&nbsp;&nbsp;<![endif]-->
<!--The following information was generated by Microsoft Office Excel's Publish
as Web Page wizard.-->
<!--If the same item is republished from Excel, all information between the DIV
tags will be replaced.-->
<!----------------------------->
<!--START OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD -->
<!----------------------------->

<div id="REPORT DETAIL SALES RESULT_23545" align=center x:publishsource="Excel">

<?php
	$today = date("d-m-y");
?>

<table border=0 cellpadding=0 cellspacing=0 width=4100 >
 <tr height=27 style='height:20.25pt'>
  <td colspan=15 height=27 class=xl5923545 width=2252 style='height:20.25pt; width:1691pt'><font class="banner"><u><b>REPORT DETAIL SALES RESULT<b></u></font></td>
  </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl1523545 style='height:12.75pt'></td>
  </tr>
 <tr class=xl6423545 height=21 style='height:15.75pt'>
  <td colspan=15 height=21 class=xl6223545 style='height:15.75pt'><font class="banner">Sponsor &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;:</td>
 </tr>
 <!-- <tr class=xl6423545 height=21 style='height:15.75pt'>
  <td colspan=15 height=21 class=xl6223545 style='height:15.75pt'>Product: ALL Product</td>
  </tr>
 <tr class=xl6423545 height=21 style='height:15.75pt'>
  <td colspan=15 height=21 class=xl6223545 style='height:15.75pt'>Campaign: ALL Campaign</td>
  </tr> -->
 <tr class=xl6423545 height=21 style='height:15.75pt'>
  <td colspan=15 height=21 class=xl6223545 style='height:15.75pt'><font class="banner">Period &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : <?php echo(_get_post('start_date'));?> s/d <?php echo(_get_post('end_date'));?></font></td>
  </tr>
 <tr class=xl6423545 height=21 style='height:15.75pt'>
  <td colspan=15 height=21 class=xl6223545 style='height:15.75pt'><font class="benner">Print Date &nbsp;&nbsp; : <?php echo($today);?></font></td>
  </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl1523545 style='height:12.75pt'></td>
 </tr>
 <tr>
  <td align="center" class="header first">No</td>
  <td align="center" class="header middle">Campaign Code</td>
  <td align="center" class="header middle">Product Code</td>
  <td align="center" class="header middle">Expected Close Date</td>
  <td align="center" class="header middle">Application No</td>
  <td align="center" class="header middle">Insured Name</td>
  <td align="center" class="header middle">Insured Gender</td>
  <td align="center" class="header middle">Insured DOB</td>
  <td align="center" class="header middle">Insured Occupation Code</td>
  <td align="center" class="header middle">Insured Occupation</td>
  <td align="center" class="header middle">Insured Job Description</td>
  <td align="center" class="header middle">Insured Occupation Class</td>
  <td align="center" class="header middle">Plans</td>
  <td align="center" class="header middle">Payment Mode</td>
  <td align="center" class="header middle">Premium</td>
  <td align="center" class="header middle">TARP</td>
  <td align="center" class="header middle">Holder Name</td>
  <td align="center" class="header middle">City</td>
  <td align="center" class="header middle">TSR Code</td>
  <td align="center" class="header middle">TSR Name</td>
  <td align="center" class="header middle">SPV Code</td>
  <td align="center" class="header middle">SPV Name</td>
  <td align="center" class="header middle">Status Application</td>
  <td align="center" class="header middle">Status Date</td>
  <td align="center" class="header middle">Spouse</td>
  <td align="center" class="header middle">First Monitoring Date</td>
  <td align="center" class="header middle">First Monitoring Status</td>
  <td align="center" class="header middle">First Monitoring By</td>
  <td align="center" class="header middle">Total Monitoring</td>
  <td align="center" class="header middle">Vcc Type</td>
 </tr>
 
 
 <?php
 $no=1;
 /////////////////////////////////////////////////////////////
 if(is_array($view_data) )
 foreach ($view_data as $campaignId => $rows) :
 
 $tarp = $rows['Premium']*12
 
 // endforeach;
 ?>
 
 <tr>
  <td class="content first" nowrap>&nbsp;<?php echo ($no++) ?></td>
  <td class="content middle right" nowrap>&nbsp; <?php echo($rows['CampaignCode']);?></td>
  <td class="content middle right">&nbsp; <?php echo($rows['ProductCode']);?></td>
  <td class="content middle right">&nbsp; <?php echo($rows['Expected']);?></td>
  <td class="content middle right">&nbsp; <?php echo($rows['Application']);?></td>
  <td class="content middle right">&nbsp; <?php echo($rows['InsuredName']);?></td>
  <td class="content middle right">&nbsp; <?php echo($rows['InsuredGender']);?></td>
  <td class="content middle right">&nbsp; <?php echo($rows['InsuredDOB']);?></td>
  <td class="content middle right">&nbsp; <?php echo(($rows['OccupationCode']?$rows['OccupationCode']:'-'));?></td>
  <td class="content middle right">&nbsp; <?php echo(($rows['InsuredOccupation']?$rows['InsuredOccupation']:'-'));?></td>
  <td class="content middle right">&nbsp; <?php echo(($rows['InsuredJobDescription']?$rows['InsuredJobDescription']:'-'));?></td>
  <td class="content middle right">&nbsp; <?php echo(($rows['InsuredOccupationClass']?$rows['InsuredOccupationClass']:'-'));?></td>
  <td class="content middle right">&nbsp; <?php echo($rows['Plans']);?></td>
  <td class="content middle right">&nbsp; <?php echo($rows['PaymentMode']);?></td>
  <td class="content middle right">&nbsp; <?php echo($rows['Premium']);?></td>
  <td class="content middle right">&nbsp; <?php echo ($tarp) ?></td>
  <td class="content middle right">&nbsp; <?php echo($rows['HolderName']);?></td>
  <td class="content middle right">&nbsp; <?php echo(($rows['City']?$rows['City']:'-'));?></td>
  <td class="content middle right">&nbsp; <?php echo($rows['TsrCode']);?></td>
  <td class="content middle right">&nbsp; <?php echo($rows['TsrName']);?></td>
  <td class="content middle right">&nbsp; <?php echo($rows['SpvCode']);?></td>
  <td class="content middle right">&nbsp; <?php echo($rows['SpvName']);?></td>
  <td class="content middle right">&nbsp; <?php echo(($rows['StatusAplication']?$rows['StatusAplication']:'-'));?></td>
  <td class="content middle right">&nbsp; <?php echo($rows['StatusDate']);?></td>
  <td class="content middle right">&nbsp; <?php echo($rows['Spouse']);?></td>
  <td class="content middle right">&nbsp; <?php echo(($rows['FirstMonitorDate']?$rows['FirstMonitorDate']:'-'));?></td>
  <td class="content middle right">&nbsp; <?php echo(($rows['FirstMonitorStatus']?$rows['FirstMonitorStatus']:'-'));?></td>
  <td class="content middle right">&nbsp; <?php echo($rows['FirstMonitorBy']);?></td>
  <td class="content middle right">&nbsp; <?php echo(count($rows['FirstMonitorBy']));?></td>
  <td class="content middle right">&nbsp; <?php echo(($rows['VccType']?$rows['VccType']:'-'));?></td>
 </tr>
 <?php
 endforeach;
 ?>
 <tr>
	<td class="total first" nowrap colspan="30">&nbsp;</td>
 </tr>	
</table>
</div>
</body>
</html>